// Generated by psc-bundle 0.11.6
var PS = {};
(function(exports) {
    "use strict";

  const express = require('express');
  const SocketServer = require('uws').Server;
  const path = require('path');

  // '{ server }' syntax doesn't seem to compile
  // neither does '(a) => ...' syntax

  exports.startServer=function() {
    const PORT = process.env.PORT || 3000;
    const INDEX = path.join(__dirname, 'dist', 'index.html');
    console.log('INDEX path: ' + INDEX);

    const server = express()
      .use(function(req, res) { res.sendFile(INDEX)})
      .listen(PORT, function() { console.log('Listening on ' + PORT) });

    const wss = new SocketServer({ server: server });

    wss.on('connection', function(ws) {
      console.log('Client connected');
      ws.on('close', function() { console.log('Client disconnected') });
    });

    setInterval(function() {
      wss.clients.forEach(function(client) {
        client.send(new Date().toTimeString());
      });
    }, 1000);
  };
})(PS["Main"] = PS["Main"] || {});
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var $foreign = PS["Main"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];        
  var main = $foreign.startServer;
  exports["main"] = main;
  exports["startServer"] = $foreign.startServer;
})(PS["Main"] = PS["Main"] || {});
PS["Main"].main();
